name: Daily Stock Alert

on:
  schedule:
    # 깃허브 서버(영국 시간) 기준이라 한국 시간에 맞춰 시/분을 계산한 세팅입니다.
    # 월요일부터 금요일까지 하루 총 3번 자동으로 실행됩니다.
    
    - cron: '10 23 * * 0-4'  # 1회차: 한국 시간 오전 08시 10분 (전날 밤 23시 10분)
    - cron: '50 03 * * 1-5'  # 2회차: 한국 시간 오후 12시 50분 (당일 새벽 03시 50분)
    - cron: '10 09 * * 1-5'  # 3회차: 한국 시간 오후 18시 10분 (당일 오전 09시 10분)

  workflow_dispatch: # 내가 원할 때 언제든 수동으로 버튼을 눌러 실행하는 기능

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: 코드 가져오기
      uses: actions/checkout@v3

    - name: 파이썬 설치
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 필요한 도구 설치
      run: |
        pip install requests beautifulsoup4

    - name: 주식 봇 실행하기
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python bot.py
